FLASK_HOST = "0.0.0.0"
FLAST_PORT = 8080
FLASK_DEBUG = True
FLASK_THREADED = True
SESSION_EXPIRE = 60000

FLASK_API_KEY = ""

MONGO_CONNECTION = "mongodb://{}:{}@127.0.0.1:27017/"
MONGO_USER = ""
MONGO_PASS = ""
MONGO_DB = ""
MONGO_ADMINS_COLLECTION = ""
MONGO_USERS_COLLECTION = ""
MONGO_CSRF_COLLECTION = ""

SERVER_IP = ""
SERVER_PORT = ""
API_URL = ""
API_USER = ""
API_PASS = ""
