FROM nginx:stable-alpine

COPY ./nginx-conf/default.conf /etc/nginx/conf.d/default.conf

COPY ./nginx-conf/nginx.conf /etc/nginx/nginx.conf

COPY ./nginx-conf/.htpasswd /etc/nginx/.htpasswd

COPY ./nginx-conf/bot_blacklist.conf /etc/nginx/bot_blacklist.conf

COPY ./nginx-conf/cert.pem /etc/ssl/certs/cert.pem

COPY ./nginx-conf/key.pem /etc/ssl/private/key.pem

COPY ./nginx-conf/cloudflare.crt /etc/ssl/certs/cloudflare.crt
