FROM python:3.9.13-alpine3.16

RUN apk add uwsgi-python3

RUN addgroup -g 1000 netadmin
RUN adduser -u 1000 -G netadmin -h /home/netadmin -D netadmin
USER netadmin

RUN mkdir -p /home/netadmin/streamflix_server

WORKDIR /home/netadmin/streamflix_server

COPY requirements.txt requirements.txt

RUN pip install --upgrade pip --user --no-warn-script-location --disable-pip-version-check
RUN pip install -r requirements.txt --user --no-warn-script-location

RUN rm requirements.txt

COPY --chown=netadmin:netadmin app_server/ .

CMD ["python", "-m", "gunicorn", "--bind", "0.0.0.0:8081", "--workers", "10", "--threads", "50", "server:app"]
