FLASK_HOST = "0.0.0.0"
FLASK_PORT = 443
FLASK_DEBUG = False
FLASK_THREADED = True
SESSION_EXPIRE = 86400
LOGGER_PATH = "./logs/app.log"

SESSION_COOKIE_SECURE = False
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "None"
SESSION_COOKIE_PATH = "/"
SESSION_COOKIE_NAME = "Cookie"

FLASK_SECRET = "flask_secret"
CSRF_TIME_TO_LIVE = 10

MONGO_CONNECTION = "mongodb://{}:{}@mongodb:27017/"
MONGO_CONNECT_TIMEOUT = 5000
MONGO_USER = ""
MONGO_PASS = ""
MONGO_DB = ""
MONGO_CSRF_COLLECTION = ""
MONGO_PLANS_COLLECTION = ""
MONGO_ADMINS_COLLECTION = ""
MONGO_SERVERS_COLLECTION = ""
MONGO_SUBSCRIBER_COLLECTION = ""

MONGO_SUBSCRIBER_COLLECTION2 = ""
