FLASK_HOST = "0.0.0.0"
FLAST_PORT = 8080
FLASK_DEBUG = True
FLASK_THREADED = True
SESSION_EXPIRE = 60000
LOGGER_PATH = ""

FLASK_SECRET = ""
CSRF_TIME_TO_LIVE = 10 #minutes

MONGO_CONNECTION = ""
MONGO_USER = ""
MONGO_PASS = ""
MONGO_DB = ""
MONGO_CSRF_COLLECTION = ""
MONGO_ADMINS_COLLECTION = ""
MONGO_SERVERS_COLLECTION = ""
MONGO_SUBSCRIBER_COLLECTION = ""

STREAMFLIX_SERVER_IP = ""
STREAMFLIX_SERVER_PORT = ""

STREAMING_CHUNK_SIZE = 10*1024