FLASK_HOST = "0.0.0.0"
FLASK_PORT = 443
FLASK_DEBUG = False
FLASK_THREADED = True
LOGGER_PATH = "./logs/server.log"

FLASK_SECRET = "flask_secret"

MONGO_CONNECTION = "mongodb://{}:{}@mongodb:27017/"
MONGO_CONNECT_TIMEOUT = 5000
MONGO_USER = ""
MONGO_PASS = ""
MONGO_DB = ""
MONGO_SERVERS_COLLECTION = ""
MONGO_SUBSCRIBER_COLLECTION = ""

# Player Settings
STREAMFLIX_SERVER_IP = "example.com"
STREAMFLIX_SERVER_PORT = FLASK_PORT
STREAMFLIX_SERVER_PROTOCOL = "https"
STREAMFLIX_SERVER_HTTPS_PORT = "443"

STREAMING_CHUNK_SIZE = 10*1024
